baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Heba Profile"
#theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "Heba Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/Logo-H.jpg"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Heba."
    subtitle: "I build things for the web"
    content: "A passionate Data Scientist & Tecnical Project Manager. I tend to Develop highly scalable production ready models for various deeplearning and statistical use cases."
    image: /images/hero.svg
    button:
      enable: true
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github/hkamel12
        - icon: fab fa-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I Experienced IT Team Leader and Trainer with many years of working knowledge of IT Service Management, Digital Transformation, Business Automation. I am currently working as a IT Team Leader  at [Nile Uiversity](https://nu.edu.eg) in Giza, Egypt. 

      I am Data Scientist & AWS Certified Machine Learning Specialty, looking to prove myself in the fields of data science, AI, and analytics and willing to work in this industry.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "SQL"
        - "Tensorflow"
        - "AWS"
        - "GCP"
        - "MongoDB"

  # Experience
  experience:
    enable: true
    items:
      - job: "Freelance Data Scientist"
        company: "Freelance"
        #companyUrl: "https://example.com"
        date: "Jan 2021 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am Modeling ML pipelines starting from data collection, data cleaning, training models, evaluation, and visualization using state-of-the-art methods."

      - job: "IT Team Leader"
        company: "Nile University"
        companyUrl: "https://nu.edu.eg"
        date: "Sep 2019 - Present"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I Manage the processing of IT, Delegate duties and tasks within the IT department.
        content: |
          I plan, organize, define milestones, and manage the implementation phases of different ICT projects to ensure timely completion and alignment with the allocated budget, and integrate cross-functional projects.

          - Lead Service Desk team.
          - Train users on software applications and provide an orientation session for both staff, faculty, and students.

      - job: "Application Support Engineer | Acting IT Manager"
        company: "Al Babtain LeBLANC"
        #companyUrl: "https://example.com"
        date: "Mar 2019 - Sep 2019"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I onduct research on existing IoT-related applications that could be useful to the market existing in Egypt or any country that we aim to conduct business in.

          - Manage Legacy Systems and maintain them.
          - Propose new enhancements to the IT infrastructure and maintain it within the company.

      - job: "Technical Support Engineer"
        company: "Zewail City"
        companyUrl: "https://www.zewailcity.edu.eg/"
        date: "Sep 2015 - Mar 2019"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I Manage help desk, Plan, direct daily activities of the team and department, lead technicians in a team environment, Administers/coordinates work schedule/assignments and supervises progress.

          - G Suite administrator manages all aspects of a G Suite domain.
          - Handle all service requests related to AD including Create Domain users, groups and set policies, Software License Server, and file share service.

      - job: "Tehnical Support Engineer"
        company: "Etisalat"
        companyUrl: "https://etisalat.eg"
        date: "Oct 2014 - Sep 2015"
        content: "I provide information, advice and technical support to a variety of clients, both professional and amateur, about problems arising from the increasing use of digital equipment and techniques. I am highly trained and able to communicate technical information, clearly and concisely, to a wide range of clients."

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Informatics"
        school:
          name: "Nile University, Egypt"
          url: "https://nu.edu.eg"
        date: "2021 - present"
        #GPA: "3.8 out of 5.0"
        #content: |-
         # Extracurricular Activities
            #- Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            #- Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Engineering in Commuication & Electronics"
        school:
          name: "Al Azhar University"
          #url: "https://example.org"
        date: "2007 - 2012"
        GPA: "3.4 out of 4.0"
        #content: |-
          #I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          #- [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          #- Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            -  AZEX (Girls Branch) Co-Founde. 
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "Knowledge officer Machine Learing Pro Program"
        school:
          name: "Knowledge Officer."
          url: "https://app.knowledgeofficer.com"
        #GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: AWS Certified Machine Learning - Specialty
        content: AWS Certified Machine Learning - Specialty.
        url: https://aws.amazon.com/
      - title: IBM Data Science Professional Certificate
        content: IBM Data Science Professional Certificate.
      #- title: Hugo Profile
        #content: Developed a theme and getting 1K+ downloads per month.
        #url: "https://github.com/gurusabarish/hugo-profile"
      #- title: Microsoft Imagine Runner
       # content: We are developed a product which can help others.
     # - title: Google Summer of Code
       # content: Contributed to a open source project.
       # url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com
